<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_robot">

  <!-- Robot Parameters -->
  <xacro:property name="base_radius" value="0.210" />
  <xacro:property name="base_height" value="0.020" />
  <xacro:property name="upper_arm_length" value="0.620" />
  <xacro:property name="lower_arm_length" value="0.880" />
  <xacro:property name="arm_thickness" value="0.015" />
  <xacro:property name="end_effector_radius" value="0.050" />
  <xacro:property name="end_effector_height" value="0.010" />
  <xacro:property name="triangle_side_length" value="0.120" />  <!-- Triangular end effector size -->
  <xacro:property name="triangle_height" value="0.010" />
  
  <!-- Calculated connection points for triangular end effector -->
  <xacro:property name="triangle_offset" value="0.035" />  <!-- Distance from triangle center to vertex -->

  <!-- Materials -->
  <material name="gris">
    <color rgba="0.55 0.55 0.55 1.0"/>
  </material>
  
  <material name="blanco">
    <color rgba="0.9 0.9 0.9 1.0"/>
  </material>
  
  <material name="colorte">
    <color rgba="0.15 0.55 0.95 1.0"/>
  </material>
  
  <material name="negro">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="verde">
    <color rgba="0.2 0.8 0.2 1.0"/>
  </material>
  
  <material name="rojo">
    <color rgba="0.8 0.2 0.2 1.0"/>
  </material>

  <!-- BASE SUPERIOR -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="negro"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.2" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.35"/>
    </inertial>
  </link>

  <!-- BRAZOS SUPERIORES (Upper Arms) -->
  
  <!-- BRAZO_1 (Arm 1) -->
  <link name="brazo1">
    <visual>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="rojo"/>
    </visual>
    <collision>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.025" iyz="0" izz="0.025"/>
    </inertial>
  </link>

  <joint name="base_brazo1" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="200.0" lower="-1.047" upper="1.047" velocity="2.0"/>
    <parent link="base_link"/>
    <child link="brazo1"/>
    <origin xyz="-0.181865335 0.105 0" rpy="0 0 2.61799"/>
  </joint>

  <!-- BRAZO_2 (Arm 2) -->
  <link name="brazo2">
    <visual>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="rojo"/>
    </visual>
    <collision>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.025" iyz="0" izz="0.025"/>
    </inertial>
  </link>

  <joint name="base_brazo2" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="200.0" lower="-1.047" upper="1.047" velocity="2.0"/>
    <parent link="base_link"/>
    <child link="brazo2"/>
    <origin xyz="0 -0.210 0" rpy="0 0 -1.57075"/>
  </joint>

  <!-- BRAZO_3 (Arm 3) -->
  <link name="brazo3">
    <visual>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="rojo"/>
    </visual>
    <collision>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upper_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.025" iyz="0" izz="0.025"/>
    </inertial>
  </link>

  <joint name="base_brazo3" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="200.0" lower="-1.047" upper="1.047" velocity="2.0"/>
    <parent link="base_link"/>
    <child link="brazo3"/>
    <origin xyz="0.181865335 0.105 0" rpy="0 0 0.523599"/>
  </joint>

  <!-- BRAZOS INFERIORES (Lower Arms) -->
  
  <!-- Ante_BRAZO_1 (Lower Arm 1) -->
  <link name="barra1_a">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="codo1_a" type="revolute">
    <axis xyz="0 -1 0"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="brazo1"/>
    <child link="barra1_a"/>
    <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="barra1_b">
    <visual>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="blanco"/>
    </visual>
    <collision>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.026" iyz="0" izz="0.026"/>
    </inertial>
  </link>

  <joint name="codo1_b" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="barra1_a"/>
    <child link="barra1_b"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Ante_BRAZO_2 (Lower Arm 2) -->
  <link name="barra2_a">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="codo2_a" type="revolute">
    <axis xyz="0 -1 0"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="brazo2"/>
    <child link="barra2_a"/>
    <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="barra2_b">
    <visual>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="blanco"/>
    </visual>
    <collision>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.008" ixy="0" ixz="0" iyy="0.026" iyz="0" izz="0.026"/>
    </inertial>
  </link>

  <joint name="codo2_b" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="barra2_a"/>
    <child link="barra2_b"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Ante_BRAZO_3 (Lower Arm 3) -->
  <link name="barra3_a">
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="codo3_a" type="revolute">
    <axis xyz="0 -1 0"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="brazo3"/>
    <child link="barra3_a"/>
    <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="barra3_b">
    <visual>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
      <material name="blanco"/>
    </visual>
    <collision>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lower_arm_length} ${arm_thickness} ${arm_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="-${lower_arm_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.008" ixy="0" ixz="0" iyy="0.026" iyz="0" izz="0.026"/>
    </inertial>
  </link>

  <joint name="codo3_b" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="100.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <parent link="barra3_a"/>
    <child link="barra3_b"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- TRIANGULAR END EFFECTOR -->
  <!-- Main triangular platform that connects all three forearms -->
  <link name="end_effector_triangle">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${triangle_height}" radius="${triangle_side_length/2}"/>
      </geometry>
      <material name="verde"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${triangle_height}" radius="${triangle_side_length/2}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.008"/>
    </inertial>
  </link>

  <!-- Primary connection: Connect triangle to forearm 1 (kinematic tree) -->
  <link name="forearm1_ee_connection">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="forearm1_ee_x" type="revolute">
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="-3.14" upper="3.14" velocity="10.0"/>
    <parent link="barra1_b"/>
    <child link="forearm1_ee_connection"/>
    <origin xyz="-${lower_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="forearm1_ee_y" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="0" lower="-3.14" upper="3.14" velocity="10.0"/>
    <parent link="forearm1_ee_connection"/>
    <child link="end_effector_triangle"/>
    <origin xyz="${triangle_offset} -${triangle_offset*0.577} 0" rpy="0 0 0"/>
  </joint>

  <!-- Visual connection points for forearms 2 and 3 (no kinematic loops) -->
  <!-- Connection point 2 visualization -->
  <link name="triangle_connection2_visual">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.008"/>
      </geometry>
      <material name="negro"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="triangle_conn2_visual" type="fixed">
    <parent link="end_effector_triangle"/>
    <child link="triangle_connection2_visual"/>
    <origin xyz="0 ${triangle_offset*1.155} 0" rpy="0 0 0"/>
  </joint>

  <!-- Connection point 3 visualization -->
  <link name="triangle_connection3_visual">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.008"/>
      </geometry>
      <material name="negro"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="triangle_conn3_visual" type="fixed">
    <parent link="end_effector_triangle"/>
    <child link="triangle_connection3_visual"/>
    <origin xyz="-${triangle_offset} -${triangle_offset*0.577} 0" rpy="0 0 0"/>
  </joint>

  <!-- Visual end points of forearms 2 and 3 -->
  <link name="forearm2_end_visual">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
      <material name="rojo"/>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="forearm2_end_joint" type="fixed">
    <parent link="barra2_b"/>
    <child link="forearm2_end_visual"/>
    <origin xyz="-${lower_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <link name="forearm3_end_visual">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
      <material name="rojo"/>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="forearm3_end_joint" type="fixed">
    <parent link="barra3_b"/>
    <child link="forearm3_end_visual"/>
    <origin xyz="-${lower_arm_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ACTUADOR (Tool mounting point on triangular end effector) -->
  <link name="actuador">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${end_effector_height}" radius="${end_effector_radius}"/>
      </geometry>
      <material name="colorte"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${end_effector_height}" radius="${end_effector_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Mount actuator to center of triangular end effector -->
  <joint name="triangle_to_actuator" type="fixed">
    <parent link="end_effector_triangle"/>
    <child link="actuador"/>
    <origin xyz="0 0 -${triangle_height/2 + end_effector_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
